"""Ordered preverb matching. Ordering and source exceptions affect the output."""

from .markers import ivd_subject_markers, tve_subject_markers

PREVERB_ORDER = {
    "ivd_present": ("gelo", "ge", "e", "cel", "ce", "do", "ye", "me", "mola", "mo", "oǩo", "ǩoǩo"),
    "ivd_past": ("gelo", "ge", "e", "cel", "ce", "do", "ye", "me", "mola", "mo", "oǩo", "ǩoǩo"),
    "ivd_future": ("gelo", "ge", "e", "cel", "ce", "do", "ye", "me", "mola", "mo", "oǩo", "ǩoǩo"),
    "ivd_pastpro": ("gelo", "ge", "e", "cel", "ce", "do", "ye", "me", "mola", "mo", "oǩo", "ǩoǩo"),
    "tve_present": (
        "gelo",
        "ge",
        "cel",
        "ce",
        "dolo",
        "do",
        "oxo",
        "me",
        "gol",
        "go",
        "oǩo",
        "gam",
        "mola",
        "ye",
        "gela",
        "ela",
        "e",
        "ceǩo",
        "eǩo",
        "ama",
        "mo",
        "ǩoǩo",
    ),
    "tve_past": (
        "gelo",
        "ge",
        "ela",
        "el",
        "e",
        "cel",
        "ce",
        "dolo",
        "do",
        "oxo",
        "me",
        "gol",
        "go",
        "oǩo",
        "gam",
        "mola",
        "ye",
        "mo",
        "ǩoǩo",
    ),
    "tve_future": (
        "gelo",
        "ge",
        "ela",
        "ele",
        "cel",
        "ce",
        "dolo",
        "do",
        "oxo",
        "me",
        "gol",
        "go",
        "oǩo",
        "gam",
        "mo",
        "ye",
        "cele",
        "mola",
        "mo",
        "ǩoǩo",
    ),
    "tve_pastpro": (
        "gelo",
        "ge",
        "ela",
        "el",
        "e",
        "cel",
        "ce",
        "dolo",
        "do",
        "oxo",
        "me",
        "gol",
        "go",
        "oǩo",
        "gam",
        "mola",
        "ye",
        "mo",
        "ǩoǩo",
    ),
    "tvm_tense": (
        "gelo",
        "ge",
        "e",
        "ce",
        "dolo",
        "do",
        "oxo",
        "me",
        "gol",
        "go",
        "oǩo",
        "gam",
        "mola",
        "ye",
        "mo",
        "ǩoǩo",
    ),
    "tvm_tve_potential": (
        "gelo",
        "ge",
        "ela",
        "e",
        "cele",
        "ce",
        "dolo",
        "do",
        "oxo",
        "me",
        "gol",
        "go",
        "oǩo",
        "gama",
        "mola",
        "mo",
        "ye",
        "ǩoǩo",
    ),
    "tvm_tve_passive": (
        "gelo",
        "ge",
        "ela",
        "e",
        "cele",
        "ce",
        "dolo",
        "do",
        "oxo",
        "me",
        "gol",
        "go",
        "oǩo",
        "gama",
        "mola",
        "mo",
        "ye",
        "ǩoǩo",
    ),
    "tvm_tve_presentperf": (
        "gelo",
        "ge",
        "ela",
        "e",
        "cele",
        "ce",
        "dolo",
        "do",
        "oxo",
        "me",
        "gol",
        "go",
        "oǩo",
        "gama",
        "mola",
        "mo",
        "ye",
        "ǩoǩo",
    ),
}

DATIVE_SPECIAL = {
    ("go",): {
        "S1_Singular": "gom",
        "S2_Singular": "gog",
        "S3_Singular": "go",
        "S1_Plural": "gom",
        "S2_Plural": "gog",
        "S3_Plural": "go",
    },
    ("gy",): {
        "S1_Singular": "gem",
        "S2_Singular": "geg",
        "S3_Singular": "gyo",
        "S1_Plural": "gem",
        "S2_Plural": "geg",
        "S3_Plural": "gyo",
    },
    ("coz",): {
        "S1_Singular": "cem",
        "S2_Singular": "ceg",
        "S3_Singular": "coz",
        "S1_Plural": "cem",
        "S2_Plural": "ceg",
        "S3_Plural": "coz",
    },
}


def get_preverbs_rules(mode: str) -> dict:
    if mode.startswith("ivd"):
        markers = dict(ivd_subject_markers)
        if mode == "ivd_present":
            markers.update(S1_Singular="om", S1_Plural="om", S2_Singular="og", S2_Plural="og")
        return {PREVERB_ORDER[mode]: markers, **DATIVE_SPECIAL}
    return {PREVERB_ORDER[mode]: tve_subject_markers}


def find_preverb(infinitive, rules, *, excluded=False):
    """Match in the source table's order; shorter preverbs can be intentional."""
    if excluded:
        return ""
    for group in rules:
        for preverb in group if isinstance(group, tuple) else (group,):
            if infinitive.startswith(preverb):
                return preverb
    return ""
