// Generated by csv-to-js-converter.py on 2025-05-24 17:05:34
// Original CSV: Test Verb Present tense.csv
// Size optimization: 34,057 bytes → 20,911 bytes

// Optimized verb list with shortened property names:
// l: Laz Infinitive
// t: Turkish Verb
// e: English Translation
export const verbList = [
  {
    "l": "avara doskudu",
    "t": "avare kalmak",
    "e": "to be idle"
  },
  {
    "l": "cebazgu",
    "t": "basmak",
    "e": "to press, to step on something"
  },
  {
    "l": "cebgaru",
    "t": "ağıt yakmak",
    "e": "to lament over something"
  },
  {
    "l": "ceçamu",
    "t": "vurmak (bir şeye)",
    "e": "to hit something/someone"
  },
  {
    "l": "ceç̌u",
    "t": "başlamak",
    "e": "to begin"
  },
  {
    "l": "cegapu",
    "t": "alışmak",
    "e": "to get used to"
  },
  {
    "l": "ceginu",
    "t": "alıştırmak",
    "e": "to get someone become familiar with something"
  },
  {
    "l": "cedginu",
    "t": "aşermek",
    "e": "to crave"
  },
  {
    "l": "celabalu",
    "t": "asmak",
    "e": "to hang"
  },
  {
    "l": "cemp̌onu",
    "t": "aşılamak",
    "e": "to vaccinate/fertilize"
  },
  {
    "l": "cexunu",
    "t": "binmek",
    "e": "to get on/ride/ascend"
  },
  {
    "l": "ceyonu",
    "t": "aşılamak",
    "e": "to vaccinate/fertilize"
  },
  {
    "l": "coxons",
    "t": "adında olmak",
    "e": "to be called"
  },
  {
    "l": "coxos gedvalu",
    "t": "adlandırmak",
    "e": "to name something/someone"
  },
  {
    "l": "cozun",
    "t": "adında olmak",
    "e": "to be called"
  },
  {
    "l": "çxomi oç̌opu",
    "t": "balık avlamak",
    "e": "to fish"
  },
  {
    "l": "diç̌irs",
    "t": "lazım gelmek",
    "e": "to require"
  },
  {
    "l": "dobadu",
    "t": "doğmak",
    "e": "to be born"
  },
  {
    "l": "dobalu",
    "t": "akıtmak",
    "e": "to pour "
  },
  {
    "l": "dobalu",
    "t": "akmak",
    "e": "to flow, to leak"
  },
  {
    "l": "dobazginapu",
    "t": "bastırmak",
    "e": "to step on the floor"
  },
  {
    "l": "dodginu",
    "t": "ayakta durmak",
    "e": "to stand"
  },
  {
    "l": "dodgitu",
    "t": "ayakta durmak",
    "e": "to stand"
  },
  {
    "l": "dodumu",
    "t": "koymak (yere)",
    "e": "to put, to place (something on the floor)"
  },
  {
    "l": "dodvumu",
    "t": "koymak (yere)",
    "e": "to put, to place (something on the floor)"
  },
  {
    "l": "doguru",
    "t": "öğrenmek",
    "e": "to learn"
  },
  {
    "l": "dogutu",
    "t": "ayakta durmak",
    "e": "to stand"
  },
  {
    "l": "doinu",
    "t": "doğurmak",
    "e": "to give birth"
  },
  {
    "l": "doǩanu",
    "t": "atmak",
    "e": "to throw"
  },
  {
    "l": "doloç̌aru",
    "t": "kaydetmek",
    "e": "to record"
  },
  {
    "l": "domçinu",
    "t": "bildirmek",
    "e": "to declare, to inform"
  },
  {
    "l": "doşinu",
    "t": "acele etmek",
    "e": "to hurry"
  },
  {
    "l": "doskidu",
    "t": "kalmak",
    "e": "to stay"
  },
  {
    "l": "dosǩudu",
    "t": "kalmak",
    "e": "to stay"
  },
  {
    "l": "doşǩvalu",
    "t": "batmak",
    "e": "to sink"
  },
  {
    "l": "dotanu",
    "t": "ağarmak (gün)",
    "e": "to dawn"
  },
  {
    "l": "dotanu",
    "t": "ağarmak (gün)",
    "e": "to dawn"
  },
  {
    "l": "doǯonu",
    "t": "sanmak",
    "e": "to think"
  },
  {
    "l": "dvaç̌irs",
    "t": "lazım gelmek",
    "e": "to require"
  },
  {
    "l": "eç̌opu",
    "t": "almak",
    "e": "to buy"
  },
  {
    "l": "elaşinu",
    "t": "anmak",
    "e": "to remember"
  },
  {
    "l": "eoçvalu",
    "t": "açmak (üzerini)",
    "e": "to open"
  },
  {
    "l": "exondvalu",
    "t": "sormluluk almak",
    "e": "to take responsibility"
  },
  {
    "l": "gamaçamu",
    "t": "satmak",
    "e": "to sell"
  },
  {
    "l": "gamaǩatu",
    "t": "ayrılmak",
    "e": "to separate, to part"
  },
  {
    "l": "gamaǩat̆u",
    "t": "ayırmak",
    "e": "to split, to separate"
  },
  {
    "l": "gamaqonu",
    "t": "dışarı çıkarmak (canlı, hareket edebilen)",
    "e": "to send off, to throw out (living being)"
  },
  {
    "l": "gamayonu",
    "t": "dışarı çıkarmak (canlı, hareket edebilen)",
    "e": "to send off, to throw out (living being)"
  },
  {
    "l": "gebažgu",
    "t": "basmak",
    "e": "to press, to step on something"
  },
  {
    "l": "geçamu",
    "t": "vurmak (bir şeye)",
    "e": "to hit something/someone"
  },
  {
    "l": "geç̌ǩu",
    "t": "başlamak",
    "e": "to begin"
  },
  {
    "l": "gegapu",
    "t": "alışmak",
    "e": "to get used to"
  },
  {
    "l": "geginu",
    "t": "alıştırmak",
    "e": "to get someone become familiar with something"
  },
  {
    "l": "geǩordinu",
    "t": "azaltmak",
    "e": "to reduce"
  },
  {
    "l": "geǩordu",
    "t": "azalmak",
    "e": "to become less, to run low"
  },
  {
    "l": "geloǩidu",
    "t": "asmak",
    "e": "to hang"
  },
  {
    "l": "gemgaru",
    "t": "ağıt yakmak",
    "e": "to lament over something"
  },
  {
    "l": "gemp̌onu",
    "t": "aşılamak",
    "e": "to vaccinate/fertilize"
  },
  {
    "l": "gent̆onu",
    "t": "batmak",
    "e": "to sink"
  },
  {
    "l": "gexunu",
    "t": "binmek",
    "e": "to get on/ride/ascend"
  },
  {
    "l": "geǯipxu",
    "t": "ayarlamak",
    "e": "arrange, set up"
  },
  {
    "l": "geǯopxu",
    "t": "ayarlamak",
    "e": "arrange, set up"
  },
  {
    "l": "giloǩidu",
    "t": "asmak",
    "e": "to hang"
  },
  {
    "l": "goǩuʒxu",
    "t": "uyanmak",
    "e": "to wake up"
  },
  {
    "l": "golusu",
    "t": "umursamamak",
    "e": "to not care"
  },
  {
    "l": "gonç̌elu",
    "t": "özlemek",
    "e": "to miss someone"
  },
  {
    "l": "gondunu",
    "t": "kaybolmak",
    "e": "to get lost"
  },
  {
    "l": "gonǯǩu",
    "t": "açmak (kapı, kilit vb.)",
    "e": "to open"
  },
  {
    "l": "gonǯu",
    "t": "açmak (kapı, kilit vb.)",
    "e": "to open"
  },
  {
    "l": "goşinu",
    "t": "hatırlamak",
    "e": "to remember"
  },
  {
    "l": "goşinu",
    "t": "hatırlatmak",
    "e": "to remind"
  },
  {
    "l": "goxiru",
    "t": "araklamak",
    "e": "to steal"
  },
  {
    "l": "guri donç̌inu",
    "t": "acımak",
    "e": "to feel pity for someone"
  },
  {
    "l": "guri meç̌valu",
    "t": "acımak",
    "e": "to feel pity for someone"
  },
  {
    "l": "guri mentxu",
    "t": "bayılmak",
    "e": "to faint"
  },
  {
    "l": "gyožin",
    "t": "adında olmak",
    "e": "to be called"
  },
  {
    "l": "ǩai doǯonu",
    "t": "beğenmek",
    "e": "to like"
  },
  {
    "l": "ǩoǩoǯalu",
    "t": "ayırmak (ikiye)",
    "e": "to divide, to detach"
  },
  {
    "l": "ǩuçxe medgalu",
    "t": "adım atmak",
    "e": "to step"
  },
  {
    "l": "lumcun",
    "t": "akşam olmak",
    "e": "to become evening"
  },
  {
    "l": "mebazgu",
    "t": "sıçmak",
    "e": "to poop"
  },
  {
    "l": "meçamu",
    "t": "vermek",
    "e": "to give"
  },
  {
    "l": "meǩap̌inu",
    "t": "atlamak",
    "e": "to jump"
  },
  {
    "l": "molaǩiru",
    "t": "bağlamak (birini/birşeyi bir yere)",
    "e": "to tie something/someone "
  },
  {
    "l": "meǩoru",
    "t": "bağlamak (birini/birşeyi bir yere)",
    "e": "to tie something/someone "
  },
  {
    "l": "meǩoru",
    "t": "bağlı olmak (birine, bir yere)",
    "e": "to be tied to something"
  },
  {
    "l": "memçinu",
    "t": "bildirmek",
    "e": "to declare, to inform"
  },
  {
    "l": "memgvapinu",
    "t": "benzetmek",
    "e": "to liken"
  },
  {
    "l": "memgvapu",
    "t": "benzemek",
    "e": "to resemble"
  },
  {
    "l": "memgvapu",
    "t": "benziyor halde olmak",
    "e": "to take after"
  },
  {
    "l": "mendoğmalu",
    "t": "almak (zorla)",
    "e": "to take something by force"
  },
  {
    "l": "meoçamu",
    "t": "beddua etmek",
    "e": "to curse"
  },
  {
    "l": "meşǩidu",
    "t": "boğmak",
    "e": "to strangle"
  },
  {
    "l": "meşǩvidu",
    "t": "boğmak",
    "e": "to strangle"
  },
  {
    "l": "meşǩvu",
    "t": "azad etmek",
    "e": "to liberate"
  },
  {
    "l": "meşvelu",
    "t": "yardım etmek",
    "e": "to help"
  },
  {
    "l": "met̆işu",
    "t": "adamak",
    "e": "to consecrate, to wow"
  },
  {
    "l": "meǯǩomilu",
    "t": "bakmak",
    "e": "to look at something, to gaze at"
  },
  {
    "l": "meǯomilu",
    "t": "bakmak",
    "e": "to look at something, to gaze at"
  },
  {
    "l": "mijaçamu",
    "t": "beddua etmek",
    "e": "to curse"
  },
  {
    "l": "moğerdinams",
    "t": "aldatmak",
    "e": "to cheat, to defraud"
  },
  {
    "l": "monžinu",
    "t": "artırmak",
    "e": "to increase (transitive)"
  },
  {
    "l": "monžinu",
    "t": "artmak",
    "e": "to increase (intransitive)"
  },
  {
    "l": "moselu",
    "t": "ayaklanmak",
    "e": "to arise"
  },
  {
    "l": "moşvacu",
    "t": "dinlenmek",
    "e": "to rest"
  },
  {
    "l": "moǯǩimu",
    "t": "açmak (üzerini)",
    "e": "to open"
  },
  {
    "l": "moǯondu",
    "t": "beğenmek",
    "e": "to like"
  },
  {
    "l": "moǯoxvalu",
    "t": "ayaklanmak",
    "e": "to arise"
  },
  {
    "l": "obadu",
    "t": "ihtiyarlamak (erkek)",
    "e": "to age (male)"
  },
  {
    "l": "obaxu",
    "t": "dovmek",
    "e": "to beat up"
  },
  {
    "l": "obgaru",
    "t": "ağlamak",
    "e": "to cry"
  },
  {
    "l": "obiru",
    "t": "şarkı söylemek",
    "e": "to sing/play"
  },
  {
    "l": "obodu",
    "t": "avarelik etmek",
    "e": "to wander around"
  },
  {
    "l": "obonu",
    "t": "vucudun bir bolumunu veya tamamını yıkamak",
    "e": "to clean (a body part)"
  },
  {
    "l": "oç̌abu",
    "t": "yapıştırmak",
    "e": "to glue"
  },
  {
    "l": "oçalişu",
    "t": "çalışmak",
    "e": "to work"
  },
  {
    "l": "oçaminu",
    "t": "kaşınmak",
    "e": "to itch"
  },
  {
    "l": "oçaminu",
    "t": "kaşımak",
    "e": "to scratch"
  },
  {
    "l": "oçamu",
    "t": "yedirmek",
    "e": "to feed"
  },
  {
    "l": "oç̌aru",
    "t": "yazmak",
    "e": "to write"
  },
  {
    "l": "oçedinu",
    "t": "aldatmak",
    "e": "to cheat, to defraud"
  },
  {
    "l": "oceru",
    "t": "inanmak",
    "e": "to believe"
  },
  {
    "l": "ocginu",
    "t": "yenmek",
    "e": "to win"
  },
  {
    "l": "oçilu",
    "t": "erkeğin evlenmesi",
    "e": "to marry (male)"
  },
  {
    "l": "oçindu",
    "t": "aksırmak",
    "e": "to sneeze"
  },
  {
    "l": "oçinu",
    "t": "tanımak",
    "e": "to know someone"
  },
  {
    "l": "oç̌ǩadu",
    "t": "çakmak",
    "e": "to flint"
  },
  {
    "l": "oçkinu",
    "t": "bilmek",
    "e": "to know"
  },
  {
    "l": "oçǩiru",
    "t": "kesmek",
    "e": "to cut"
  },
  {
    "l": "oç̌ǩiru",
    "t": "biçmek",
    "e": "to mow (with a knife/hook)"
  },
  {
    "l": "oç̌ǩomu",
    "t": "yemek",
    "e": "to eat"
  },
  {
    "l": "oç̌ǩoru",
    "t": "biçmek",
    "e": "to mow (with a knife/hook)"
  },
  {
    "l": "oçodinu",
    "t": "bitirmek",
    "e": "to finish/complete"
  },
  {
    "l": "oçodu",
    "t": "bitmek",
    "e": "to end"
  },
  {
    "l": "oç̌opu",
    "t": "yakalamak",
    "e": "to catch"
  },
  {
    "l": "ocoxu",
    "t": "çağırmak",
    "e": "to call someone"
  },
  {
    "l": "oçu",
    "t": "beklemek",
    "e": "to wait"
  },
  {
    "l": "oçindu",
    "t": "aksırmak",
    "e": "to sneeze"
  },
  {
    "l": "oç̌u",
    "t": "acımak (his)",
    "e": "to ache"
  },
  {
    "l": "oç̌u",
    "t": "acıtmak",
    "e": "to hurt someone"
  },
  {
    "l": "oç̌uç̌u",
    "t": "göz kırpmak",
    "e": "to wink"
  },
  {
    "l": "oçxomu",
    "t": "balık avlamak",
    "e": "to fish"
  },
  {
    "l": "oğarğalu",
    "t": "konuşmak",
    "e": "to speak"
  },
  {
    "l": "oğaru",
    "t": "çizmek",
    "e": "to draw"
  },
  {
    "l": "ogibu",
    "t": "haşlamak, pişmek",
    "e": "to boil"
  },
  {
    "l": "ogibu",
    "t": "haşlanmak",
    "e": "to be boiled"
  },
  {
    "l": "ognu",
    "t": "duymak",
    "e": "to hear"
  },
  {
    "l": "ogoru",
    "t": "istemek, aramak",
    "e": "to look, to want"
  },
  {
    "l": "oğuru",
    "t": "ölmek",
    "e": "to die"
  },
  {
    "l": "ogzalu",
    "t": "yürümek",
    "e": "to walk"
  },
  {
    "l": "ogzu",
    "t": "çalıştırmak",
    "e": "to make something work"
  },
  {
    "l": "oju",
    "t": "uçmak",
    "e": "to fly"
  },
  {
    "l": "ojginu",
    "t": "yenmek",
    "e": "to win"
  },
  {
    "l": "okadu",
    "t": "adamak",
    "e": "to consecrate, to wow"
  },
  {
    "l": "oǩap̌u",
    "t": "koşmak",
    "e": "to run"
  },
  {
    "l": "oǩiru",
    "t": "bağlamak",
    "e": "to tie"
  },
  {
    "l": "oǩiru",
    "t": "bağlamak (birini/birşeyi bir yere)",
    "e": "to tie something/someone"
  },
  {
    "l": "oǩitxu",
    "t": "sormak/okumak",
    "e": "to ask/read"
  },
  {
    "l": "oǩiu",
    "t": "azarlamak",
    "e": "to bawl out"
  },
  {
    "l": "oǩobğu",
    "t": "biriktirmek",
    "e": "to save (money)"
  },
  {
    "l": "oǩoğmalu",
    "t": "biriktirmek",
    "e": "to save (money)"
  },
  {
    "l": "oǩonağuru",
    "t": "bayılmak",
    "e": "to faint"
  },
  {
    "l": "oǩont̆alu",
    "t": "birleştirmek",
    "e": "to unite/join"
  },
  {
    "l": "oǩoreʒxu",
    "t": "ağıt yakmak",
    "e": "to lament over something"
  },
  {
    "l": "oǩorinu",
    "t": "azaltmak",
    "e": "to reduce"
  },
  {
    "l": "oǩortu",
    "t": "ayırmak",
    "e": "to split, to separate"
  },
  {
    "l": "oǩoru",
    "t": "bağlamak",
    "e": "to connect, to tie"
  },
  {
    "l": "okosu",
    "t": "süpürmek",
    "e": "to sweep"
  },
  {
    "l": "oǩovelu",
    "t": "anlaşmak",
    "e": "to come to an agreement"
  },
  {
    "l": "oǩoǯǩu",
    "t": "ayırmak (ikiye)",
    "e": "to divide, to detach"
  },
  {
    "l": "oǩriu",
    "t": "azarlamak",
    "e": "to bawl out"
  },
  {
    "l": "oǩriu",
    "t": "bağırmak",
    "e": "to shout, to scream"
  },
  {
    "l": "olafu",
    "t": "konuşmak",
    "e": "to speak"
  },
  {
    "l": "olaǩirdu",
    "t": "konuşmak",
    "e": "to speak"
  },
  {
    "l": "olalu",
    "t": "havlamak, boş konuşmak",
    "e": "to bark, to talk nonsene "
  },
  {
    "l": "olasiru",
    "t": "bilemek",
    "e": "to grind/sharpen"
  },
  {
    "l": "olast̆u",
    "t": "bilemek",
    "e": "to grind/sharpen"
  },
  {
    "l": "olaxinu",
    "t": "azdırmak",
    "e": "to lead astray, to turn mad"
  },
  {
    "l": "olimbu",
    "t": "sevmek",
    "e": "to love"
  },
  {
    "l": "olva",
    "t": "gitmek",
    "e": "to go"
  },
  {
    "l": "omç̌eşu",
    "t": "beklemek",
    "e": "to wait"
  },
  {
    "l": "omçinu",
    "t": "bildirmek",
    "e": "to declare, to inform"
  },
  {
    "l": "omç̌ǩeşu",
    "t": "beklemek",
    "e": "to wait"
  },
  {
    "l": "omç̌u",
    "t": "acele etmek",
    "e": "to hurry"
  },
  {
    "l": "omçviru",
    "t": "yüzmek",
    "e": "to swim"
  },
  {
    "l": "omç̌vu",
    "t": "acele etmek",
    "e": "to hurry"
  },
  {
    "l": "omeselu",
    "t": "anlatmak",
    "e": "to explain"
  },
  {
    "l": "omgaru",
    "t": "ağlamak",
    "e": "to cry, to weep"
  },
  {
    "l": "omǩolanu",
    "t": "acılaşmak",
    "e": "to get bitter"
  },
  {
    "l": "omku",
    "t": "öğütmek",
    "e": "to grind"
  },
  {
    "l": "omkvu",
    "t": "öğütmek",
    "e": "to grind"
  },
  {
    "l": "omonǩanu",
    "t": "ağırlaşmak",
    "e": "to get heavier"
  },
  {
    "l": "omşkironu",
    "t": "acıkmak",
    "e": "to be hungry"
  },
  {
    "l": "omşkorinu",
    "t": "acıkmak",
    "e": "to be hungry"
  },
  {
    "l": "omʒikanu",
    "t": "azalmak",
    "e": "to become less, to run low"
  },
  {
    "l": "onaxu",
    "t": "çamaşır yıkamak",
    "e": "to clean laundry"
  },
  {
    "l": "onç̌aru",
    "t": "yazmak",
    "e": "to write"
  },
  {
    "l": "oncğore ovapu",
    "t": "arlanmak",
    "e": "to be ashamed"
  },
  {
    "l": "oncğore oyapu",
    "t": "arlanmak",
    "e": "to be ashamed"
  },
  {
    "l": "oncğori oǩvapu",
    "t": "arlanmak",
    "e": "to be ashamed"
  },
  {
    "l": "onciru",
    "t": "uyumak",
    "e": "to sleep"
  },
  {
    "l": "onçiru",
    "t": "yüzmek",
    "e": "to swim"
  },
  {
    "l": "onçviru",
    "t": "yüzmek",
    "e": "to swim"
  },
  {
    "l": "onǩanu",
    "t": "kımıldamak",
    "e": "to move slightly"
  },
  {
    "l": "onǩap̌u",
    "t": "koşmak",
    "e": "to run"
  },
  {
    "l": "onǩilu",
    "t": "kilitlemek",
    "e": "to lock"
  },
  {
    "l": "op̌aramitu",
    "t": "konuşmak",
    "e": "to speak"
  },
  {
    "l": "opatxu",
    "t": "1.silkelemek 2. hafifçe dövmek",
    "e": "to shake off, to beat lightly"
  },
  {
    "l": "op̌içvu",
    "t": "oruç tutmak",
    "e": "to fast"
  },
  {
    "l": "op̌içu",
    "t": "oruç tutmak",
    "e": "to fast"
  },
  {
    "l": "op̌lanu",
    "t": "avunmak",
    "e": "to be consoled"
  },
  {
    "l": "op̌lanu",
    "t": "avutmak",
    "e": "to comfort"
  },
  {
    "l": "op̌riǩanu",
    "t": "acılaşmak",
    "e": "to get bitter"
  },
  {
    "l": "oputxu",
    "t": "uçmak",
    "e": "to fly"
  },
  {
    "l": "oqominu",
    "t": "susamak",
    "e": "to be thirsty"
  },
  {
    "l": "oqondinu",
    "t": "beklemek",
    "e": "to wait"
  },
  {
    "l": "oqoropu",
    "t": "sevmek",
    "e": "to love"
  },
  {
    "l": "oqru",
    "t": "bağırmak",
    "e": "to shout, to scream"
  },
  {
    "l": "oqvapu",
    "t": "biri için birşey olmak",
    "e": "to be something/someone (to someone)"
  },
  {
    "l": "oqvilu",
    "t": "vurarak öldürmek",
    "e": "to kill by shooting"
  },
  {
    "l": "ordu",
    "t": "büyütmek ",
    "e": "to raise"
  },
  {
    "l": "ordu",
    "t": "büyümek ",
    "e": "to grow up"
  },
  {
    "l": "oropu",
    "t": "sevmek",
    "e": "to love"
  },
  {
    "l": "oropu",
    "t": "sevmek",
    "e": "to love"
  },
  {
    "l": "osiminu",
    "t": "dinlemek",
    "e": "to listen"
  },
  {
    "l": "osinapu",
    "t": "konuşmak",
    "e": "to speak"
  },
  {
    "l": "oşinu",
    "t": "saygı göstermek",
    "e": "to respect"
  },
  {
    "l": "oşiru",
    "t": "aşındırmak",
    "e": "to erode, corrode"
  },
  {
    "l": "oşit̆inu",
    "t": "aksırmak",
    "e": "to sneeze"
  },
  {
    "l": "oskedinu",
    "t": "besleyerek yaşatmak, yaşamda tutmak",
    "e": "to raise, to keep someone alive"
  },
  {
    "l": "oskidu",
    "t": "yaşamak",
    "e": "to live"
  },
  {
    "l": "oşǩinu",
    "t": "dinlemek",
    "e": "to listen"
  },
  {
    "l": "osǩudu",
    "t": "yaşamak",
    "e": "to live"
  },
  {
    "l": "oşǩunu",
    "t": "bilmek",
    "e": "to know"
  },
  {
    "l": "oşǩidu",
    "t": "boğulmak",
    "e": "to drown"
  },
  {
    "l": "oşǩomu",
    "t": "yemek",
    "e": "to eat"
  },
  {
    "l": "oşǩoru",
    "t": "biçmek",
    "e": "to mow (with a knife/hook)"
  },
  {
    "l": "oşolu",
    "t": "ıslanmak",
    "e": "to get wet"
  },
  {
    "l": "osteru",
    "t": "oynamak",
    "e": "to play"
  },
  {
    "l": "ostu",
    "t": "kaymak",
    "e": "to slip"
  },
  {
    "l": "ost̆u",
    "t": "kaymak",
    "e": "to slip"
  },
  {
    "l": "oşu",
    "t": "içmek",
    "e": "to drink"
  },
  {
    "l": "oşvacu",
    "t": "dinlenmek",
    "e": "to rest"
  },
  {
    "l": "osvaru",
    "t": "sıraya dizmek",
    "e": "to line up"
  },
  {
    "l": "ot̆rağodu",
    "t": "şarkı söylemek",
    "e": "to sing"
  },
  {
    "l": "otanu",
    "t": "aydınlatmak",
    "e": "to brighten"
  },
  {
    "l": "ot̆at̆u",
    "t": "bulaştırmak",
    "e": "to contaminate"
  },
  {
    "l": "ot̆axu",
    "t": "kırmak",
    "e": "to break"
  },
  {
    "l": "otiru",
    "t": "taşımak",
    "e": "to carry"
  },
  {
    "l": "ot̆işu",
    "t": "başarmak",
    "e": "to accomplish, to succeed"
  },
  {
    "l": "ot̆ǩoçu",
    "t": "atılmak",
    "e": "to rush forward"
  },
  {
    "l": "ot̆ǩoçu",
    "t": "atmak",
    "e": "to throw"
  },
  {
    "l": "otku",
    "t": "söylemek",
    "e": "to say"
  },
  {
    "l": "ot̆ǩu",
    "t": "söylemek",
    "e": "to say"
  },
  {
    "l": "otoru",
    "t": "taşımak",
    "e": "to carry"
  },
  {
    "l": "oucu",
    "t": "dinlemek",
    "e": "to listen"
  },
  {
    "l": "ovalu",
    "t": "el sallamak",
    "e": "to waive"
  },
  {
    "l": "ovapu",
    "t": "biri için birşey olmak",
    "e": "to be something/someone (to someone)"
  },
  {
    "l": "ovapu",
    "t": "olmak",
    "e": "to be"
  },
  {
    "l": "oxaçǩu",
    "t": "tohum ekmek",
    "e": "to sow"
  },
  {
    "l": "oxap̌aru",
    "t": "konuşmak",
    "e": "to speak"
  },
  {
    "l": "oxaresiru",
    "t": "affetmek",
    "e": "to forgive"
  },
  {
    "l": "oxarsuvu",
    "t": "affetmek",
    "e": "to forgive"
  },
  {
    "l": "oxarsuvu",
    "t": "bağlamak",
    "e": "to connect, to tie"
  },
  {
    "l": "oxat̆iru",
    "t": "affetmek",
    "e": "to forgive"
  },
  {
    "l": "oxaziru",
    "t": "hazırlamak",
    "e": "to prepare"
  },
  {
    "l": "oxažiru",
    "t": "hazırlamak",
    "e": "to prepare"
  },
  {
    "l": "oxçinu",
    "t": "kadının yaşlanması",
    "e": "to age (female)"
  },
  {
    "l": "oxelu",
    "t": "sevinmek",
    "e": "to be happy"
  },
  {
    "l": "oxenu",
    "t": "yapmak",
    "e": "to do"
  },
  {
    "l": "oxerxu",
    "t": "biçmek (testere ile)",
    "e": "to mow (with a saw)"
  },
  {
    "l": "oxmaru",
    "t": "kullanmak",
    "e": "to use"
  },
  {
    "l": "oxomu",
    "t": "kurumak",
    "e": "to dry"
  },
  {
    "l": "oxop̌u",
    "t": "küremek",
    "e": "to shovel up"
  },
  {
    "l": "oxoşkvinu",
    "t": "azad etmek",
    "e": "to liberate"
  },
  {
    "l": "oxoǯonu",
    "t": "anlamak",
    "e": "to understand"
  },
  {
    "l": "oxtimu",
    "t": "gitmek",
    "e": "to go"
  },
  {
    "l": "oxu",
    "t": "küremek",
    "e": "to shovel up"
  },
  {
    "l": "oxvenu",
    "t": "yapmak",
    "e": "to do"
  },
  {
    "l": "oyapu",
    "t": "olmak",
    "e": "to be"
  },
  {
    "l": "oyapu",
    "t": "olmak",
    "e": "to become"
  },
  {
    "l": "oyondrinu",
    "t": "bekletmek",
    "e": "to make someone wait"
  },
  {
    "l": "oyondru",
    "t": "beklemek",
    "e": "to wait"
  },
  {
    "l": "oyoxu",
    "t": "çağırmak",
    "e": "to call someone"
  },
  {
    "l": "ožiru",
    "t": "görmek",
    "e": "to see"
  },
  {
    "l": "ožiru",
    "t": "görmek",
    "e": "to see"
  },
  {
    "l": "ožiʒu",
    "t": "gulmek",
    "e": "to laugh"
  },
  {
    "l": "oʒadu",
    "t": "bakmak (birine)",
    "e": "to look after someone"
  },
  {
    "l": "oǯamu",
    "t": "öldürmek",
    "e": "to kill"
  },
  {
    "l": "oǯilu",
    "t": "koparmak",
    "e": "to pluck"
  },
  {
    "l": "oǯǩaru",
    "t": "sulamak",
    "e": "to water"
  },
  {
    "l": "oǯǩidu",
    "t": "örmek",
    "e": "to build"
  },
  {
    "l": "oǯǩu",
    "t": "sokmak",
    "e": "to insert"
  },
  {
    "l": "oǯǩunu",
    "t": "ağrımak",
    "e": "to ache"
  },
  {
    "l": "oǯǩunu",
    "t": "ağrımak",
    "e": "to ache"
  },
  {
    "l": "oǯǩunu",
    "t": "ağrıtmak",
    "e": "to hurt someone"
  },
  {
    "l": "oǯodu",
    "t": "örmek",
    "e": "to build"
  },
  {
    "l": "oǯu",
    "t": "azdırmak",
    "e": "to lead astray, to turn mad"
  },
  {
    "l": "oǯunu",
    "t": "ağrımak",
    "e": "to ache"
  },
  {
    "l": "oǯunu",
    "t": "ağrıtmak",
    "e": "to hurt someone"
  },
  {
    "l": "oʒxunu",
    "t": "ayıklamak",
    "e": "to weed out"
  },
  {
    "l": "oʒxunu",
    "t": "ayrım yapmak",
    "e": "to distinguish, to differentiate"
  },
  {
    "l": "ren",
    "t": "olmak",
    "e": "to be"
  },
  {
    "l": "uğun",
    "t": "var (cansız)",
    "e": "to have"
  },
  {
    "l": "unon",
    "t": "istemek",
    "e": "to want"
  },
  {
    "l": "uqoun",
    "t": "var (canlı)",
    "e": "to have"
  },
  {
    "l": "uyonun",
    "t": "var (canlı)",
    "e": "to have"
  },
  {
    "l": "xe oǩoç̌apxu",
    "t": "alkışlamak",
    "e": "to applause"
  },
  {
    "l": "yeç̌opu",
    "t": "almak",
    "e": "to buy"
  },
  {
    "l": "yoxo cedvalu",
    "t": "adlandırmak",
    "e": "to name something/someone"
  },
  {
    "l": "zop̌ini",
    "t": "bahsetmek",
    "e": "to mention, to talk about"
  },
  {
    "l": "gexvamu",
    "t": "kutlamak",
    "e": "to celebrate"
  },
  {
    "l": "cexvamu",
    "t": "kutlamak",
    "e": "to celebrate"
  }
];

// Search function that handles all three languages
export const processVerbSearch = (searchTerm, verbs = verbList) => {
  if (!searchTerm) return verbs;
  
  const searchLower = searchTerm.toLowerCase().trim();
  return verbs.filter(verb => 
    verb.l.toLowerCase().includes(searchLower) ||
    verb.t.toLowerCase().includes(searchLower) ||
    verb.e.toLowerCase().includes(searchLower)
  );
};

// Format a verb for display (converts short keys to full names)
export const formatVerbForDisplay = (verb) => ({
  'Laz Infinitive': verb.l,
  'Turkish Verb': verb.t,
  'English Translation': verb.e
});

// Format the entire list for display
export const formatVerbListForDisplay = (verbs = verbList) => 
  verbs.map(formatVerbForDisplay);

// Get verb by Laz infinitive
export const getVerbByInfinitive = (infinitive) => 
  verbList.find(v => v.l.toLowerCase() === infinitive.toLowerCase());

// Function to check if a verb exists
export const verbExists = (infinitive) => 
  verbList.some(v => v.l.toLowerCase() === infinitive.toLowerCase());
