CREATE TABLE dialect (
  dialect_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  english_name TEXT NOT NULL,
  turkish_name TEXT NOT NULL,
  laz_name TEXT NOT NULL
);

INSERT INTO dialect (english_name, turkish_name, laz_name)
VALUES
  ('Ardeşen', 'Ardeşen', 'Ardeşen'),
  ('Hopa', 'Hopa', 'Xopa');




SELECT * FROM dialect;


DROP SCHEMA schema;