-- schema.sql (run inside the laz_test database)
-- Purpose: create tables and relationships (no seed data)

CREATE TABLE IF NOT EXISTS dialect (
  dialect_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  english_name VARCHAR(20) NOT NULL,
  turkish_name VARCHAR(20) NOT NULL,
  laz_name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS verb_category (
  verb_category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  english_name VARCHAR(20) NOT NULL,
  turkish_name VARCHAR(20) NOT NULL,
  laz_name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS verb_family (
  verb_family_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- optional: a human label/code for the family (useful for debugging/admin UI)
  family_code VARCHAR(20) UNIQUE
);

CREATE TABLE IF NOT EXISTS preverb (
  preverb_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  spelling VARCHAR(20) NOT NULL UNIQUE,
  preverb_group VARCHAR(20),   -- e.g., 'ce' or 'ge' (optional but useful)
  notes TEXT -- “TEXT makes sense here because the length is unbounded and user-authored.”
);

CREATE TABLE IF NOT EXISTS verb (
  verb_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  verb_family_id INTEGER REFERENCES verb_family(verb_family_id),
  dialect_id INTEGER NOT NULL REFERENCES dialect(dialect_id),
  verb_category_id INTEGER NOT NULL REFERENCES verb_category(verb_category_id),

  infinitive VARCHAR(20) NOT NULL,
  present_3sg VARCHAR(20) NOT NULL,

  meaning_english TEXT NOT NULL, -- “TEXT makes sense here because the length is unbounded and user-authored.”
  meaning_turkish TEXT NOT NULL,

 -- Verb-level requirements
  requires_marker BOOLEAN NOT NULL DEFAULT FALSE,


  -- keep these only if they're truly verb-level toggles; otherwise model via preverb tables
  allows_optional_prefix_ko BOOLEAN NOT NULL DEFAULT FALSE,
  allows_optional_prefix_do BOOLEAN NOT NULL DEFAULT FALSE,

  -- prevent duplicates within a dialect
  CONSTRAINT verb_unique_in_dialect UNIQUE (dialect_id, infinitive)
);

CREATE TABLE verb_preverb (
  verb_id INTEGER NOT NULL REFERENCES verb(verb_id) ON DELETE CASCADE,
  preverb_id INTEGER NOT NULL REFERENCES preverb(preverb_id) ON DELETE RESTRICT,
  PRIMARY KEY (verb_id, preverb_id)
);




CREATE TABLE IF NOT EXISTS verb_form (
  verb_form_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Which verb (dialect-specific)
  verb_id INTEGER NOT NULL
    REFERENCES verb(verb_id)
    ON DELETE CASCADE,

  -- Arguments
  subject person NOT NULL,
  object person,

  -- Tense / derivation (UI: "Aspect")
  tense tense,
  derivation derivation NOT NULL DEFAULT 'none',

  -- Clause properties
  mood mood NOT NULL DEFAULT 'indicative',

  -- Morphological operations (structure only for now)
  is_applicative BOOLEAN NOT NULL DEFAULT FALSE,
  is_causative BOOLEAN NOT NULL DEFAULT FALSE,        -- oldurgan (single causative)
  is_double_causative BOOLEAN NOT NULL DEFAULT FALSE, -- ettirgen (double causative)


  -- Final surface form
  spelling VARCHAR(20) NOT NULL
);
