-- schema.sql (run inside the laz_test database)
-- Purpose: create tables and relationships (no seed data)

CREATE TABLE IF NOT EXISTS dialect (
  dialect_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  english_name TEXT NOT NULL,
  turkish_name TEXT NOT NULL,
  laz_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS verb_category (
  verb_category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  english_name TEXT NOT NULL,
  turkish_name TEXT NOT NULL,
  laz_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS verb_family (
  verb_family_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- optional: a human label/code for the family (useful for debugging/admin UI)
  family_code TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS preverb (
  preverb_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  spelling TEXT NOT NULL UNIQUE,
  preverb_group TEXT,   -- e.g., 'ce' or 'ge' (optional but useful)
  notes TEXT
);

CREATE TABLE IF NOT EXISTS verb (
  verb_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  verb_family_id INTEGER REFERENCES verb_family(verb_family_id),
  dialect_id INTEGER NOT NULL REFERENCES dialect(dialect_id),
  verb_category_id INTEGER NOT NULL REFERENCES verb_category(verb_category_id),

  infinitive TEXT NOT NULL,
  present_3sg TEXT NOT NULL,

  meaning_english TEXT NOT NULL,
  meaning_turkish TEXT NOT NULL,

 -- Verb-level requirements
  requires_marker BOOLEAN NOT NULL DEFAULT FALSE,


  -- keep these only if they're truly verb-level toggles; otherwise model via preverb tables
  has_optional_preverb_ko BOOLEAN NOT NULL DEFAULT FALSE,
  has_optional_preverb_do BOOLEAN NOT NULL DEFAULT FALSE,

  -- prevent duplicates within a dialect
  CONSTRAINT verb_unique_in_dialect UNIQUE (dialect_id, infinitive)
);

-- Many-to-many: which preverbs are allowed for a verb family
CREATE TABLE IF NOT EXISTS verb_family_preverb (
  verb_family_id INTEGER NOT NULL REFERENCES verb_family(verb_family_id) ON DELETE CASCADE,
  preverb_id INTEGER NOT NULL REFERENCES preverb(preverb_id) ON DELETE CASCADE,

  is_optional BOOLEAN NOT NULL DEFAULT FALSE,
  is_productive BOOLEAN NOT NULL DEFAULT TRUE,

  PRIMARY KEY (verb_family_id, preverb_id)
);

-- Dialect-specific allow/deny (for ce/ge split, or other regional constraints)
CREATE TABLE IF NOT EXISTS verb_family_preverb_dialect (
  verb_family_id INTEGER NOT NULL REFERENCES verb_family(verb_family_id) ON DELETE CASCADE,
  preverb_id INTEGER NOT NULL REFERENCES preverb(preverb_id) ON DELETE CASCADE,
  dialect_id INTEGER NOT NULL REFERENCES dialect(dialect_id) ON DELETE CASCADE,

  is_allowed BOOLEAN NOT NULL DEFAULT TRUE,

  PRIMARY KEY (verb_family_id, preverb_id, dialect_id)
);


CREATE TABLE IF NOT EXISTS verb_form (
  verb_form_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Which verb (dialect-specific)
  verb_id INTEGER NOT NULL
    REFERENCES verb(verb_id)
    ON DELETE CASCADE,

  -- Arguments
  subject person NOT NULL,
  object person,

  -- Tense / derivation (UI: "Aspect")
  tense tense,
  derivation derivation NOT NULL DEFAULT 'none',

  -- Clause properties
  mood mood NOT NULL DEFAULT 'indicative',

  -- Morphological operations (structure only for now)
  is_applicative BOOLEAN NOT NULL DEFAULT FALSE,
  is_causative BOOLEAN NOT NULL DEFAULT FALSE,        -- oldurgan (single causative)
  is_double_causative BOOLEAN NOT NULL DEFAULT FALSE, -- ettirgen (double causative)


  -- Final surface form
  spelling TEXT NOT NULL
);
