from ..common import Person, Region

PRESENT_NOMINATIVE_SUFFIXES = {
    "en": {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "er",
            Person.SECOND_SINGULAR: "er",
            Person.THIRD_SINGULAR: "en",
            Person.FIRST_PLURAL: "ert",
            Person.SECOND_PLURAL: "ert",
            Person.THIRD_PLURAL: "enan",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "er",
            Person.SECOND_SINGULAR: "er",
            Person.THIRD_SINGULAR: "en",
            Person.FIRST_PLURAL: "ert",
            Person.SECOND_PLURAL: "ert",
            Person.THIRD_PLURAL: "enan",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "er",
            Person.SECOND_SINGULAR: "er",
            Person.THIRD_SINGULAR: "en",
            Person.FIRST_PLURAL: "ert",
            Person.SECOND_PLURAL: "ert",
            Person.THIRD_PLURAL: "enan",
        },
        Region.HOPA: {
            Person.FIRST_SINGULAR: "er",
            Person.SECOND_SINGULAR: "er",
            Person.THIRD_SINGULAR: "en",
            Person.FIRST_PLURAL: "ert",
            Person.SECOND_PLURAL: "ert",
            Person.THIRD_PLURAL: "enan",
        },
    },
    "un": {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "ur",
            Person.SECOND_SINGULAR: "ur",
            Person.THIRD_SINGULAR: "un",
            Person.FIRST_PLURAL: "urt",
            Person.SECOND_PLURAL: "urt",
            Person.THIRD_PLURAL: "unan",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "ur",
            Person.SECOND_SINGULAR: "ur",
            Person.THIRD_SINGULAR: "un",
            Person.FIRST_PLURAL: "urt",
            Person.SECOND_PLURAL: "urt",
            Person.THIRD_PLURAL: "unan",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "ur",
            Person.SECOND_SINGULAR: "ur",
            Person.THIRD_SINGULAR: "un",
            Person.FIRST_PLURAL: "urt",
            Person.SECOND_PLURAL: "urt",
            Person.THIRD_PLURAL: "unan",
        },
        Region.HOPA: {
            Person.FIRST_SINGULAR: "ur",
            Person.SECOND_SINGULAR: "ur",
            Person.THIRD_SINGULAR: "un",
            Person.FIRST_PLURAL: "urt",
            Person.SECOND_PLURAL: "urt",
            Person.THIRD_PLURAL: "unan",
        },
    },
}

PRESENT_ERGATIVE_SUFFIXES = {
    "ams": {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "ay",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "ams",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "ams",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.HOPA: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "ams",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
    },
}

APPLICATIVE_PREFIXES = {
    Person.FIRST_SINGULAR: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "vi",
            Person.SECOND_SINGULAR: "mi",
            Person.THIRD_SINGULAR: "mi",
            Person.SECOND_PLURAL: "mi",
            Person.THIRD_PLURAL: "mi",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "vi",
            Person.SECOND_SINGULAR: "mi",
            Person.THIRD_SINGULAR: "mi",
            Person.SECOND_PLURAL: "mi",
            Person.THIRD_PLURAL: "mi",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "bi",
            Person.SECOND_SINGULAR: "mi",
            Person.THIRD_SINGULAR: "mi",
            Person.SECOND_PLURAL: "mi",
            Person.THIRD_PLURAL: "mi",
        },
    },
    Person.SECOND_SINGULAR: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "gi",
            Person.SECOND_SINGULAR: "i",
            Person.THIRD_SINGULAR: "gi",
            Person.FIRST_PLURAL: "gi",
            Person.THIRD_PLURAL: "gi",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "gi",
            Person.SECOND_SINGULAR: "i",
            Person.THIRD_SINGULAR: "gi",
            Person.FIRST_PLURAL: "gi",
            Person.THIRD_PLURAL: "gi",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "gi",
            Person.SECOND_SINGULAR: "i",
            Person.THIRD_SINGULAR: "gi",
            Person.FIRST_PLURAL: "gi",
            Person.THIRD_PLURAL: "gi",
        },
    },
    Person.THIRD_SINGULAR: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "vu",
            Person.SECOND_SINGULAR: "u",
            Person.THIRD_SINGULAR: "u",
            Person.FIRST_PLURAL: "vu",
            Person.SECOND_PLURAL: "u",
            Person.THIRD_PLURAL: "u",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "vu",
            Person.SECOND_SINGULAR: "u",
            Person.THIRD_SINGULAR: "u",
            Person.FIRST_PLURAL: "vu",
            Person.SECOND_PLURAL: "u",
            Person.THIRD_PLURAL: "u",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "bu",
            Person.SECOND_SINGULAR: "u",
            Person.THIRD_SINGULAR: "u",
            Person.FIRST_PLURAL: "bu",
            Person.SECOND_PLURAL: "u",
            Person.THIRD_PLURAL: "u",
        },
    },
    Person.FIRST_PLURAL: {
        Region.ARDESEN: {
            Person.SECOND_SINGULAR: "mi",
            Person.THIRD_SINGULAR: "mi",
            Person.FIRST_PLURAL: "vi",
            Person.SECOND_PLURAL: "mi",
            Person.THIRD_PLURAL: "mi",
        },
        Region.PAZAR: {
            Person.SECOND_SINGULAR: "mi",
            Person.THIRD_SINGULAR: "mi",
            Person.FIRST_PLURAL: "vi",
            Person.SECOND_PLURAL: "mi",
            Person.THIRD_PLURAL: "mi",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.SECOND_SINGULAR: "mi",
            Person.THIRD_SINGULAR: "mi",
            Person.FIRST_PLURAL: "bi",
            Person.SECOND_PLURAL: "mi",
            Person.THIRD_PLURAL: "mi",
        },
    },
    Person.SECOND_PLURAL: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "gi",
            Person.THIRD_SINGULAR: "gi",
            Person.FIRST_PLURAL: "gi",
            Person.SECOND_PLURAL: "i",
            Person.THIRD_PLURAL: "gi",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "gi",
            Person.THIRD_SINGULAR: "gi",
            Person.FIRST_PLURAL: "gi",
            Person.SECOND_PLURAL: "i",
            Person.THIRD_PLURAL: "gi",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "gi",
            Person.THIRD_SINGULAR: "gi",
            Person.FIRST_PLURAL: "gi",
            Person.SECOND_PLURAL: "i",
            Person.THIRD_PLURAL: "gi",
        },
    },
    Person.THIRD_PLURAL: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "vu",
            Person.SECOND_SINGULAR: "u",
            Person.THIRD_SINGULAR: "u",
            Person.FIRST_PLURAL: "vu",
            Person.SECOND_PLURAL: "u",
            Person.THIRD_PLURAL: "u",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "vu",
            Person.SECOND_SINGULAR: "u",
            Person.THIRD_SINGULAR: "u",
            Person.FIRST_PLURAL: "vu",
            Person.SECOND_PLURAL: "u",
            Person.THIRD_PLURAL: "u",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "bu",
            Person.SECOND_SINGULAR: "u",
            Person.THIRD_SINGULAR: "u",
            Person.FIRST_PLURAL: "bu",
            Person.SECOND_PLURAL: "u",
            Person.THIRD_PLURAL: "u",
        },
    },
}

CAUSATIVE_PREFIXES = {
    Person.FIRST_SINGULAR: {
        Region.ARDESEN: {
            Person.SECOND_SINGULAR: "mo",
            Person.THIRD_SINGULAR: "mo",
            Person.SECOND_PLURAL: "mo",
            Person.THIRD_PLURAL: "mo",
        },
        Region.PAZAR: {
            Person.SECOND_SINGULAR: "mo",
            Person.THIRD_SINGULAR: "mo",
            Person.SECOND_PLURAL: "mo",
            Person.THIRD_PLURAL: "mo",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.SECOND_SINGULAR: "mo",
            Person.THIRD_SINGULAR: "mo",
            Person.SECOND_PLURAL: "mo",
            Person.THIRD_PLURAL: "mo",
        },
    },
    Person.SECOND_SINGULAR: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "go",
            Person.THIRD_SINGULAR: "go",
            Person.FIRST_PLURAL: "go",
            Person.THIRD_PLURAL: "go",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "go",
            Person.THIRD_SINGULAR: "go",
            Person.FIRST_PLURAL: "go",
            Person.THIRD_PLURAL: "go",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "go",
            Person.THIRD_SINGULAR: "go",
            Person.FIRST_PLURAL: "go",
            Person.THIRD_PLURAL: "go",
        },
    },
    Person.THIRD_SINGULAR: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "vo",
            Person.SECOND_SINGULAR: "o",
            Person.THIRD_SINGULAR: "o",
            Person.FIRST_PLURAL: "vo",
            Person.SECOND_PLURAL: "o",
            Person.THIRD_PLURAL: "o",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "vo",
            Person.SECOND_SINGULAR: "o",
            Person.THIRD_SINGULAR: "o",
            Person.FIRST_PLURAL: "vo",
            Person.SECOND_PLURAL: "o",
            Person.THIRD_PLURAL: "o",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "bo",
            Person.SECOND_SINGULAR: "o",
            Person.THIRD_SINGULAR: "o",
            Person.FIRST_PLURAL: "bo",
            Person.SECOND_PLURAL: "o",
            Person.THIRD_PLURAL: "o",
        },
    },
    Person.FIRST_PLURAL: {
        Region.ARDESEN: {
            Person.SECOND_SINGULAR: "mo",
            Person.THIRD_SINGULAR: "mo",
            Person.SECOND_PLURAL: "mo",
            Person.THIRD_PLURAL: "mo",
        },
        Region.PAZAR: {
            Person.SECOND_SINGULAR: "mo",
            Person.THIRD_SINGULAR: "mo",
            Person.SECOND_PLURAL: "mo",
            Person.THIRD_PLURAL: "mo",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.SECOND_SINGULAR: "mo",
            Person.THIRD_SINGULAR: "mo",
            Person.SECOND_PLURAL: "mo",
            Person.THIRD_PLURAL: "mo",
        },
    },
    Person.SECOND_PLURAL: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "go",
            Person.THIRD_SINGULAR: "go",
            Person.FIRST_PLURAL: "go",
            Person.THIRD_PLURAL: "go",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "go",
            Person.THIRD_SINGULAR: "go",
            Person.FIRST_PLURAL: "go",
            Person.THIRD_PLURAL: "go",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "go",
            Person.THIRD_SINGULAR: "go",
            Person.FIRST_PLURAL: "go",
            Person.THIRD_PLURAL: "go",
        },
    },
    Person.THIRD_PLURAL: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "vo",
            Person.SECOND_SINGULAR: "o",
            Person.THIRD_SINGULAR: "o",
            Person.FIRST_PLURAL: "vo",
            Person.SECOND_PLURAL: "o",
            Person.THIRD_PLURAL: "o",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "vo",
            Person.SECOND_SINGULAR: "o",
            Person.THIRD_SINGULAR: "o",
            Person.FIRST_PLURAL: "vo",
            Person.SECOND_PLURAL: "o",
            Person.THIRD_PLURAL: "o",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "bo",
            Person.SECOND_SINGULAR: "o",
            Person.THIRD_SINGULAR: "o",
            Person.FIRST_PLURAL: "bo",
            Person.SECOND_PLURAL: "o",
            Person.THIRD_PLURAL: "o",
        },
    },
}

APPLICATIVE_SUFFIXES = {
    Person.FIRST_SINGULAR: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "ay",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "ams",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "ams",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
    },
    Person.SECOND_SINGULAR: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "ay",
            Person.FIRST_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "ams",
            Person.FIRST_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "ams",
            Person.FIRST_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
    },
    Person.THIRD_SINGULAR: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "ay",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "ams",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "ams",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
    },
    Person.FIRST_PLURAL: {
        Region.ARDESEN: {
            Person.SECOND_SINGULAR: "amt",
            Person.THIRD_SINGULAR: "aman",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.PAZAR: {
            Person.SECOND_SINGULAR: "amt",
            Person.THIRD_SINGULAR: "aman",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.SECOND_SINGULAR: "amt",
            Person.THIRD_SINGULAR: "aman",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
    },
    Person.SECOND_PLURAL: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "amt",
            Person.THIRD_SINGULAR: "aman",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "amt",
            Person.THIRD_SINGULAR: "aman",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "amt",
            Person.THIRD_SINGULAR: "aman",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
    },
    Person.THIRD_PLURAL: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "aman",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "aman",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "am",
            Person.SECOND_SINGULAR: "am",
            Person.THIRD_SINGULAR: "aman",
            Person.FIRST_PLURAL: "amt",
            Person.SECOND_PLURAL: "amt",
            Person.THIRD_PLURAL: "aman",
        },
    },
}

OPTATIVE_SUFFIXES = {
    Person.FIRST_SINGULAR: {
        Region.ARDESEN: {
            Person.SECOND_SINGULAR: "a",
            Person.THIRD_SINGULAR: "ay",
            Person.SECOND_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
        Region.PAZAR: {
            Person.SECOND_SINGULAR: "a",
            Person.THIRD_SINGULAR: "as",
            Person.SECOND_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.SECOND_SINGULAR: "a",
            Person.THIRD_SINGULAR: "as",
            Person.SECOND_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
    },
    Person.SECOND_SINGULAR: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "a",
            Person.THIRD_SINGULAR: "ay",
            Person.FIRST_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "a",
            Person.THIRD_SINGULAR: "as",
            Person.FIRST_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "a",
            Person.THIRD_SINGULAR: "as",
            Person.FIRST_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
    },
    Person.THIRD_SINGULAR: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "a",
            Person.SECOND_SINGULAR: "a",
            Person.THIRD_SINGULAR: "ay",
            Person.FIRST_PLURAL: "at",
            Person.SECOND_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "a",
            Person.SECOND_SINGULAR: "a",
            Person.THIRD_SINGULAR: "as",
            Person.FIRST_PLURAL: "at",
            Person.SECOND_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "a",
            Person.SECOND_SINGULAR: "a",
            Person.THIRD_SINGULAR: "as",
            Person.FIRST_PLURAL: "at",
            Person.SECOND_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
    },
    Person.FIRST_PLURAL: {
        Region.ARDESEN: {
            Person.SECOND_SINGULAR: "a",
            Person.THIRD_SINGULAR: "an",
            Person.SECOND_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
        Region.PAZAR: {
            Person.SECOND_SINGULAR: "a",
            Person.THIRD_SINGULAR: "an",
            Person.SECOND_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.SECOND_SINGULAR: "a",
            Person.THIRD_SINGULAR: "an",
            Person.SECOND_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
    },
    Person.SECOND_PLURAL: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "a",
            Person.THIRD_SINGULAR: "an",
            Person.FIRST_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "a",
            Person.THIRD_SINGULAR: "an",
            Person.FIRST_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "a",
            Person.THIRD_SINGULAR: "an",
            Person.FIRST_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
    },
    Person.THIRD_PLURAL: {
        Region.ARDESEN: {
            Person.FIRST_SINGULAR: "a",
            Person.SECOND_SINGULAR: "a",
            Person.THIRD_SINGULAR: "ay",
            Person.FIRST_PLURAL: "at",
            Person.SECOND_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
        Region.PAZAR: {
            Person.FIRST_SINGULAR: "a",
            Person.SECOND_SINGULAR: "a",
            Person.THIRD_SINGULAR: "as",
            Person.FIRST_PLURAL: "at",
            Person.SECOND_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
        Region.FINDIKLI_ARHAVI: {
            Person.FIRST_SINGULAR: "a",
            Person.SECOND_SINGULAR: "a",
            Person.THIRD_SINGULAR: "as",
            Person.FIRST_PLURAL: "at",
            Person.SECOND_PLURAL: "at",
            Person.THIRD_PLURAL: "an",
        },
    },
}
