from .do_preverb import DO_PREVERB_APPLICATIVE_PREFIXES, DO_PREVERB_PREFIXES

PREVERB_PREFIXES_TABLE = {"do": DO_PREVERB_PREFIXES}

PREVERB_APPLICATIVE_PREFIXES_TABLE = {"do": DO_PREVERB_APPLICATIVE_PREFIXES}
