from .do_preverb import (DO_PREVERB_APPLICATIVE_PREFIXES,
                         DO_PREVERB_CAUSATIVE_PREFIXES, DO_PREVERB_PREFIXES)

MUTATED_PREVERB_PREFIXES_TABLE = {"do": DO_PREVERB_PREFIXES}

PREVERB_APPLICATIVE_PREFIXES_TABLE = {"do": DO_PREVERB_APPLICATIVE_PREFIXES}

PREVERB_CAUSATIVE_PREFIXES_TABLE = {"do": DO_PREVERB_CAUSATIVE_PREFIXES}
