// Generated by csv-to-js-converter.py on 2024-12-10 19:48:50
// Original CSV: Test Verb Present tense.csv
// Size optimization: 28,700 bytes → 17,654 bytes

// Optimized verb list with shortened property names:
// l: Laz Infinitive
// t: Turkish Verb
// e: English Translation
export const verbList = [
    {
      "l": "ceçamu",
      "t": "vurmak (bir şeye)",
      "e": "to hit something/someone"
    },
    {
      "l": "ceç̌u",
      "t": "başlamak",
      "e": "to begin"
    },
    {
      "l": "coxons",
      "t": "adında olmak",
      "e": "to be called"
    },
    {
      "l": "cozun",
      "t": "adında olmak",
      "e": "to be called"
    },
    {
      "l": "diç̌irs",
      "t": "lazım gelmek",
      "e": "to require"
    },
    {
      "l": "dodumu",
      "t": "koymak (yere)",
      "e": "to put, to place (something on the floor)"
    },
    {
      "l": "dodvumu",
      "t": "koymak (yere)",
      "e": "to put, to place (something on the floor)"
    },
    {
      "l": "doguru",
      "t": "öğrenmek",
      "e": "to learn"
    },
    {
      "l": "doloç̌aru",
      "t": "kaydetmek",
      "e": "to record"
    },
    {
      "l": "doskidu",
      "t": "kalmak",
      "e": "to stay"
    },
    {
      "l": "doǯonu",
      "t": "sanmak",
      "e": "to think"
    },
    {
      "l": "dvaç̌irs",
      "t": "lazım gelmek",
      "e": "to require"
    },
    {
      "l": "eç̌opu",
      "t": "almak",
      "e": "to buy"
    },
    {
      "l": "exondvalu",
      "t": "sormluluk almak",
      "e": "to take responsibility"
    },
    {
      "l": "gamaçamu",
      "t": "satmak",
      "e": "to sell"
    },
    {
      "l": "geçamu",
      "t": "vurmak (bir şeye)",
      "e": "to hit something/someone"
    },
    {
      "l": "geç̌ǩu",
      "t": "başlamak",
      "e": "to begin"
    },
    {
      "l": "gonç̌elu",
      "t": "özlemek",
      "e": "to miss someone"
    },
    {
      "l": "gonǯǩu",
      "t": "açmak (kapı, kilit vb.)",
      "e": "to open"
    },
    {
      "l": "gonǯu",
      "t": "açmak (kapı, kilit vb.)",
      "e": "to open"
    },
    {
      "l": "goşinu",
      "t": "hatırlamak",
      "e": "to remember"
    },
    {
      "l": "goşinu",
      "t": "hatırlatmak",
      "e": "to remind"
    },
    {
      "l": "gyožin",
      "t": "adında olmak",
      "e": "to be called"
    },
    {
      "l": "ǩai doǯonu",
      "t": "beğenmek",
      "e": "to like"
    },
    {
      "l": "mebazgu",
      "t": "sıçmak",
      "e": "to poop"
    },
    {
      "l": "meçamu",
      "t": "vermek",
      "e": "to give"
    },
    {
      "l": "moşvacu",
      "t": "dinlemek",
      "e": "to rest"
    },
    {
      "l": "obgaru",
      "t": "ağlamak",
      "e": "to cry"
    },
    {
      "l": "obiru",
      "t": "şarkı söylemek",
      "e": "to sing/play"
    },
    {
      "l": "oçamu",
      "t": "yedirmek",
      "e": "to feed"
    },
    {
      "l": "oç̌aru",
      "t": "yazmak",
      "e": "to write"
    },
    {
      "l": "oçinu",
      "t": "tanımak",
      "e": "to know someone"
    },
    {
      "l": "oçkinu",
      "t": "bilmek",
      "e": "to know"
    },
    {
      "l": "oç̌ǩomu",
      "t": "yemek",
      "e": "to eat"
    },
    {
      "l": "oç̌opu",
      "t": "yakalamak",
      "e": "to catch"
    },
    {
      "l": "ocoxu",
      "t": "çağırmak",
      "e": "to call someone"
    },
    {
      "l": "oğarğalu",
      "t": "konuşmak",
      "e": "to speak"
    },
    {
      "l": "oğaru",
      "t": "çizmek",
      "e": "to draw"
    },
    {
      "l": "ognu",
      "t": "duymak",
      "e": "to hear"
    },
    {
      "l": "ogoru",
      "t": "istemek, aramak",
      "e": "to look, to want"
    },
    {
      "l": "oğuru",
      "t": "ölmek",
      "e": "to die"
    },
    {
      "l": "ogzu",
      "t": "çalıştırmak",
      "e": "to make something work"
    },
    {
      "l": "oju",
      "t": "uçmak",
      "e": "to fly"
    },
    {
      "l": "oǩap̌u",
      "t": "koşmak",
      "e": "to run"
    },
    {
      "l": "okosu",
      "t": "süpürmek",
      "e": "to sweep"
    },
    {
      "l": "olafu",
      "t": "konuşmak",
      "e": "to speak"
    },
    {
      "l": "olaǩirdu",
      "t": "konuşmak",
      "e": "to speak"
    },
    {
      "l": "olalu",
      "t": "havlamak, boş konuşmak",
      "e": "to bark, to talk nonsene "
    },
    {
      "l": "olimbu",
      "t": "sevmek",
      "e": "to love"
    },
    {
      "l": "olva",
      "t": "gitmek",
      "e": "to go"
    },
    {
      "l": "omçviru",
      "t": "yüzmek",
      "e": "to swim"
    },
    {
      "l": "omgaru",
      "t": "ağlamak",
      "e": "to cry, to weep"
    },
    {
      "l": "omku",
      "t": "öğütmek",
      "e": "to grind"
    },
    {
      "l": "omkvu",
      "t": "öğütmek",
      "e": "to grind"
    },
    {
      "l": "omşkironu",
      "t": "acıkmak",
      "e": "to be hungry"
    },
    {
      "l": "omşkorinu",
      "t": "acıkmak",
      "e": "to be hungry"
    },
    {
      "l": "onç̌aru",
      "t": "yazmak",
      "e": "to write"
    },
    {
      "l": "onciru",
      "t": "uyumak",
      "e": "to sleep"
    },
    {
      "l": "onçiru",
      "t": "yüzmek",
      "e": "to swim"
    },
    {
      "l": "onǩap̌u",
      "t": "koşmak",
      "e": "to run"
    },
    {
      "l": "op̌aramitu",
      "t": "konuşmak",
      "e": "to speak"
    },
    {
      "l": "oputxu",
      "t": "uçmak",
      "e": "to fly"
    },
    {
      "l": "oqvapu",
      "t": "biri için birşey olmak",
      "e": "to be something/someone (to someone)"
    },
    {
      "l": "oropu",
      "t": "sevmek",
      "e": "to love"
    },
    {
      "l": "osinapu",
      "t": "konuşmak",
      "e": "to speak"
    },
    {
      "l": "oşinu",
      "t": "saygı göstermek",
      "e": "to respect"
    },
    {
      "l": "oskedinu",
      "t": "besleyerek yaşatmak, yaşamda tutmak",
      "e": "to raise, to keep someone alive"
    },
    {
      "l": "oskidu",
      "t": "yaşamak",
      "e": "to live"
    },
    {
      "l": "oşǩomu",
      "t": "yemek",
      "e": "to eat"
    },
    {
      "l": "osteru",
      "t": "oynamak",
      "e": "to play"
    },
    {
      "l": "oşu",
      "t": "içmek",
      "e": "to drink"
    },
    {
      "l": "ot̆ağodu",
      "t": "şarkı söylemek",
      "e": "to sing"
    },
    {
      "l": "ot̆axu",
      "t": "kırmak",
      "e": "to break"
    },
    {
      "l": "otku",
      "t": "söylemek",
      "e": "to say"
    },
    {
      "l": "ot̆ǩu",
      "t": "söylemek",
      "e": "to say"
    },
    {
      "l": "otoru",
      "t": "taşımak",
      "e": "to carry"
    },
    {
      "l": "ovapu",
      "t": "biri için birşey olmak",
      "e": "to be something/someone (to someone)"
    },
    {
      "l": "ovapu",
      "t": "olmak",
      "e": "to be"
    },
    {
      "l": "oxap̌aru",
      "t": "konuşmak",
      "e": "to speak"
    },
    {
      "l": "oxenu",
      "t": "yapmak",
      "e": "to do"
    },
    {
      "l": "oxop̌u",
      "t": "küremek",
      "e": "to shovel up"
    },
    {
      "l": "oxoǯonu",
      "t": "anlamak",
      "e": "to understand"
    },
    {
      "l": "oxtimu",
      "t": "gitmek",
      "e": "to go"
    },
    {
      "l": "oxu",
      "t": "küremek",
      "e": "to shovel up"
    },
    {
      "l": "oxvenu",
      "t": "yapmak",
      "e": "to do"
    },
    {
      "l": "oyapu",
      "t": "olmak",
      "e": "to be"
    },
    {
      "l": "oyapu",
      "t": "olmak",
      "e": "to become"
    },
    {
      "l": "oyoxu",
      "t": "çağırmak",
      "e": "to call someone"
    },
    {
      "l": "oǯilu",
      "t": "koparmak",
      "e": "to pluck"
    },
    {
      "l": "oǯǩidu",
      "t": "örmek",
      "e": "to build"
    },
    {
      "l": "oǯǩunu",
      "t": "ağrımak",
      "e": "to ache"
    },
    {
      "l": "oǯǩunu",
      "t": "ağrımak",
      "e": "to ache"
    },
    {
      "l": "oǯodu",
      "t": "örmek",
      "e": "to build"
    },
    {
      "l": "oǯunu",
      "t": "ağrımak",
      "e": "to ache"
    },
    {
      "l": "ren",
      "t": "olmak",
      "e": "to be"
    },
    {
      "l": "uğun",
      "t": "var (cansız)",
      "e": "to have"
    },
    {
      "l": "unon",
      "t": "istemek",
      "e": "to want"
    },
    {
      "l": "uqonun",
      "t": "var (cansız)",
      "e": "to have"
    },
    {
      "l": "uyonun",
      "t": "var (canlı)",
      "e": "to have"
    },
    {
      "l": "xe oǩoç̌apxu",
      "t": "alkışlamak",
      "e": "to applause"
    },
    {
      "l": "yeç̌opu",
      "t": "almak",
      "e": "to buy"
    },
    {
      "l": "meşvelu",
      "t": "yardım etmek",
      "e": "to help"
    },
    {
      "l": "oǩitxu",
      "t": "sormak/okumak",
      "e": "to ask/read"
    },
    {
      "l": "gondunu",
      "t": "kaybolmak",
      "e": "to get lost"
    },
    {
      "l": "ordu",
      "t": "büyütmek ",
      "e": "to raise"
    },
    {
      "l": "onǩilu",
      "t": "kilitlemek",
      "e": "to lock"
    },
    {
      "l": "oçǩiru",
      "t": "kesmek",
      "e": "to cut"
    },
    {
      "l": "oǩiru",
      "t": "bağlamak",
      "e": "to tie"
    },
    {
      "l": "obaxu",
      "t": "dovmek",
      "e": "to beat up"
    },
    {
      "l": "oǯamu",
      "t": "oldurmek",
      "e": "to kill"
    },
    {
      "l": "obonu",
      "t": "vucudun bir bolumunu veya tamamını yıkamak",
      "e": "to burn oneself"
    },
    {
      "l": "oceru",
      "t": "inanmak",
      "e": "to believe"
    },
    {
      "l": "oçaminu",
      "t": "kaşınmak",
      "e": "to itch"
    },
    {
      "l": "oçaminu",
      "t": "kaşımak",
      "e": "to scratch"
    },
    {
      "l": "oçilu",
      "t": "erkeğin evlenmesi",
      "e": "to marry (male)"
    },
    {
      "l": "oç̌abu",
      "t": "yapıştırmak",
      "e": "to glue"
    },
    {
      "l": "oç̌ǩadu",
      "t": "çakmak",
      "e": "to flint"
    },
    {
      "l": "ožiʒu",
      "t": "gulmek",
      "e": "to laugh"
    },
    {
      "l": "doşinu",
      "t": "acele etmek",
      "e": "to hurry"
    },
    {
      "l": "omç̌u",
      "t": "acele etmek",
      "e": "to hurry"
    },
    {
      "l": "omǩolanu",
      "t": "acılaşmak",
      "e": "to get bitter"
    },
    {
      "l": "op̌riǩanu",
      "t": "acılaşmak",
      "e": "to get bitter"
    },
    {
      "l": "oç̌u",
      "t": "acımak (his)",
      "e": "to ache"
    },
    {
      "l": "guri meç̌valu",
      "t": "acımak",
      "e": "to feel pity for someone"
    },
    {
      "l": "guri donç̌inu",
      "t": "acımak",
      "e": "to feel pity for someone"
    },
    {
      "l": "oç̌u",
      "t": "acıtmak",
      "e": "to hurt someone"
    },
    {
      "l": "eoçvalu",
      "t": "açmak (üzerini)",
      "e": "to open"
    },
    {
      "l": "moǯǩimu",
      "t": "açmak (üzerini)",
      "e": "to open"
    },
    {
      "l": "okadu",
      "t": "adamak",
      "e": "to consecrate, to wow"
    },
    {
      "l": "met̆işu",
      "t": "adamak",
      "e": "to consecrate, to wow"
    },
    {
      "l": "ǩuçxe medgalu",
      "t": "adım atmak",
      "e": "to step"
    },
    {
      "l": "coxos gedvalu",
      "t": "adlandırmak",
      "e": "to name something/someone"
    },
    {
      "l": "yoxo cedvalu",
      "t": "adlandırmak",
      "e": "to name something/someone"
    },
    {
      "l": "oxarsuvu",
      "t": "affetmek",
      "e": "to forgive"
    },
    {
      "l": "oxaresiru",
      "t": "affetmek",
      "e": "to forgive"
    },
    {
      "l": "oxat̆iru",
      "t": "affetmek",
      "e": "to forgive"
    },
    {
      "l": "dotanu",
      "t": "ağarmak (gün)",
      "e": "to dawn"
    },
    {
      "l": "dotanu",
      "t": "ağarmak (gün)",
      "e": "to dawn"
    },
    {
      "l": "omonǩanu",
      "t": "ağırlaşmak",
      "e": "to get heavier"
    },
    {
      "l": "oǩoreʒxu",
      "t": "ağıt yakmak",
      "e": "to lament over something"
    },
    {
      "l": "gemgaru",
      "t": "ağıt yakmak",
      "e": "to lament over something"
    },
    {
      "l": "cebgaru",
      "t": "ağıt yakmak",
      "e": "to lament over something"
    },
    {
      "l": "oǯunu",
      "t": "ağrıtmak",
      "e": "to hurt someone"
    },
    {
      "l": "oǯǩunu",
      "t": "ağrıtmak",
      "e": "to hurt someone"
    },
    {
      "l": "dobalu",
      "t": "akıtmak",
      "e": "to pour "
    },
    {
      "l": "dobalu",
      "t": "akmak",
      "e": "to flow, to leak"
    },
    {
      "l": "oçindu",
      "t": "aksırmak",
      "e": "to sneeze"
    },
    {
      "l": "oşit̆inu",
      "t": "aksırmak",
      "e": "to sneeze"
    },
    {
      "l": "akşam olmak",
      "t": "akşam olmak",
      "e": "to become evening"
    },
    {
      "l": "moğerdinu",
      "t": "aldatmak",
      "e": "to cheat, to defraud"
    },
    {
      "l": "moğerdinams",
      "t": "aldatmak",
      "e": "to cheat, to defraud"
    },
    {
      "l": "oçedinu",
      "t": "aldatmak",
      "e": "to cheat, to defraud"
    },
    {
      "l": "gegapu",
      "t": "alışmak",
      "e": "to get used to"
    },
    {
      "l": "cegapu",
      "t": "alışmak",
      "e": "to get used to"
    },
    {
      "l": "geginu",
      "t": "alıştırmak",
      "e": "to get someone become familiar with something"
    },
    {
      "l": "ceginu",
      "t": "alıştırmak",
      "e": "to get someone become familiar with something"
    },
    {
      "l": "mendoğmalu",
      "t": "almak (zorla)",
      "e": "to take something by force"
    },
    {
      "l": "oǩovelu",
      "t": "anlaşmak",
      "e": "to come to an agreement"
    },
    {
      "l": "omeselu",
      "t": "anlatmak",
      "e": "to explain"
    },
    {
      "l": "elaşinu",
      "t": "anmak",
      "e": "to remember"
    },
    {
      "l": "goxiru",
      "t": "araklamak",
      "e": "to steal"
    },
    {
      "l": "oncğore oyapu",
      "t": "arlanmak",
      "e": "to be ashamed"
    },
    {
      "l": "oncğore ovapu",
      "t": "arlanmak",
      "e": "to be ashamed"
    },
    {
      "l": "oncğori oǩvapu",
      "t": "arlanmak",
      "e": "to be ashamed"
    },
    {
      "l": "monžinu",
      "t": "artırmak",
      "e": "to increase (transitive)"
    },
    {
      "l": "monžinu",
      "t": "artmak",
      "e": "to increase (intransitive)"
    },
    {
      "l": "geloǩidu",
      "t": "asmak",
      "e": "to hang"
    },
    {
      "l": "giloǩidu",
      "t": "asmak",
      "e": "to hang"
    },
    {
      "l": "celabalu",
      "t": "asmak",
      "e": "to hang"
    },
    {
      "l": "ceginu",
      "t": "aşermek",
      "e": "to crave"
    },
    {
      "l": "oqoropu",
      "t": "sevmek",
      "e": "to love"
    },
    {
      "l": "oropu",
      "t": "sevmek",
      "e": "to love"
    },
    {
      "l": "ceyonu",
      "t": "aşılamak",
      "e": "to vaccinate/fertilize"
    },
    {
      "l": "gemp̌onu",
      "t": "aşılamak",
      "e": "to vaccinate/fertilize"
    },
    {
      "l": "cemp̌onu",
      "t": "aşılamak",
      "e": "to vaccinate/fertilize"
    },
    {
      "l": "oşiru",
      "t": "aşındırmak",
      "e": "to erode, corrode"
    },
    {
      "l": "ot̆ǩoçu",
      "t": "atılmak",
      "e": "to rush forward"
    },
    {
      "l": "meǩap̌inu",
      "t": "atlamak",
      "e": "to jump"
    },
    {
      "l": "ot̆ǩoçu",
      "t": "atmak",
      "e": "to throw"
    },
    {
      "l": "doǩanu",
      "t": "atmak",
      "e": "to throw"
    },
    {
      "l": "obodu",
      "t": "avarelik etmek",
      "e": "to wander around"
    },
    {
      "l": "op̌lanu",
      "t": "avunmak",
      "e": "to be consoled"
    },
    {
      "l": "op̌lanu",
      "t": "avutmak",
      "e": "to comfort"
    },
    {
      "l": "moǯoxvalu",
      "t": "ayaklanmak",
      "e": "to arise"
    },
    {
      "l": "moselu",
      "t": "ayaklanmak",
      "e": "to arise"
    },
    {
      "l": "dodgitu",
      "t": "ayakta durmak",
      "e": "to stand"
    },
    {
      "l": "dogutu",
      "t": "ayakta durmak",
      "e": "to stand"
    },
    {
      "l": "dodginu",
      "t": "ayakta durmak",
      "e": "to stand"
    },
    {
      "l": "geǯopxu",
      "t": "ayarlamak",
      "e": "arrange, set up"
    },
    {
      "l": "geǯipxu",
      "t": "ayarlamak",
      "e": "arrange, set up"
    },
    {
      "l": "otanu",
      "t": "aydınlatmak",
      "e": "to brighten"
    },
    {
      "l": "oǩortu",
      "t": "ayırmak",
      "e": "to split, to separate"
    },
    {
      "l": "gamaǩat̆u",
      "t": "ayırmak",
      "e": "to split, to separate"
    },
    {
      "l": "oǩoǯǩu",
      "t": "ayırmak (ikiye)",
      "e": "to divide, to detach"
    },
    {
      "l": "ǩoǩoǯalu",
      "t": "ayırmak (ikiye)",
      "e": "to divide, to detach"
    },
    {
      "l": "gamaǩatu",
      "t": "ayrılmak",
      "e": "to separate, to part"
    },
    {
      "l": "oʒxunu",
      "t": "ayrım yapmak",
      "e": "to distinguish, to differentiate"
    },
    {
      "l": "oxoşkvinu",
      "t": "azad etmek",
      "e": "to liberate"
    },
    {
      "l": "meşǩvu",
      "t": "azad etmek",
      "e": "to liberate"
    },
    {
      "l": "omʒikanu",
      "t": "azalmak",
      "e": "to become less, to run low"
    },
    {
      "l": "geǩordu",
      "t": "azalmak",
      "e": "to become less, to run low"
    },
    {
      "l": "oǩorinu",
      "t": "azaltmak",
      "e": "to reduce"
    },
    {
      "l": "geǩordinu",
      "t": "azaltmak",
      "e": "to reduce"
    },
    {
      "l": "oǩriu",
      "t": "azarlamak",
      "e": "to bawl out"
    },
    {
      "l": "oǩiu",
      "t": "azarlamak",
      "e": "to bawl out"
    },
    {
      "l": "olaxinu",
      "t": "azdırmak",
      "e": "to lead astray, to turn mad"
    },
    {
      "l": "oǯu",
      "t": "azdırmak",
      "e": "to lead astray, to turn mad"
    },
    {
      "l": "oqru",
      "t": "bağırmak",
      "e": "to shout, to scream"
    },
    {
      "l": "oǩriu",
      "t": "bağırmak",
      "e": "to shout, to scream"
    },
    {
      "l": "oxarsuvu",
      "t": "bağlamak",
      "e": "to connect, to tie"
    },
    {
      "l": "oǩoru",
      "t": "bağlamak",
      "e": "to connect, to tie"
    },
    {
      "l": "oǩiru",
      "t": "bağlamak (birini/birşeyi bir yere)",
      "e": "to tie something/someone"
    },
    {
      "l": "meǩoru",
      "t": "bağlamak (birini/birşeyi bir yere)",
      "e": "to tie something/someone "
    },
    {
      "l": "meǩiru",
      "t": "bağlamak (birini/birşeyi bir yere)",
      "e": "to tie something/someone "
    },
    {
      "l": "meǩoru",
      "t": "bağlanmak",
      "e": "to be connected, to be attached"
    },
    {
      "l": "meǩoru",
      "t": "bağlı olmak (birine, bir yere)",
      "e": "to be tied to something"
    },
    {
      "l": "zop̌ini",
      "t": "bahsetmek",
      "e": "to mention, to talk about"
    },
    {
      "l": "oʒadu",
      "t": "bakmak (birine)",
      "e": "to look after someone"
    },
    {
      "l": "meǯǩomilu",
      "t": "bakmak",
      "e": "to look at something, to gaze at"
    },
    {
      "l": "meǯomilu",
      "t": "bakmak",
      "e": "to look at something, to gaze at"
    },
    {
      "l": "oçxomu",
      "t": "balık avlamak",
      "e": "to fish"
    },
    {
      "l": "çxomi oç̌opu",
      "t": "balık avlamak",
      "e": "to fish"
    },
    {
      "l": "gebažgu",
      "t": "basmak",
      "e": "to press, to step on something"
    },
    {
      "l": "cebazgu",
      "t": "basmak",
      "e": "to press, to step on something"
    },
    {
      "l": "dobazginapu",
      "t": "bastırmak",
      "e": "to step on the floor"
    },
    {
      "l": "ot̆işu",
      "t": "başarmak",
      "e": "to accomplish, to succeed"
    },
    {
      "l": "doşǩvalu",
      "t": "batmak",
      "e": "to sink"
    },
    {
      "l": "gent̆onu",
      "t": "batmak",
      "e": "to sink"
    },
    {
      "l": "guri mentxalu",
      "t": "bayılmak",
      "e": "to faint"
    },
    {
      "l": "oǩonağuru",
      "t": "bayılmak",
      "e": "to faint"
    },
    {
      "l": "meoçamu",
      "t": "beddua etmek",
      "e": "to curse"
    },
    {
      "l": "mijaçamu",
      "t": "beddua etmek",
      "e": "to curse"
    },
    {
      "l": "moǯondu",
      "t": "beğenmek",
      "e": "to like"
    },
    {
      "l": "moǯondu",
      "t": "beğenmek",
      "e": "to like"
    },
    {
      "l": "omç̌ǩeşu",
      "t": "beklemek",
      "e": "to wait"
    },
    {
      "l": "omç̌eşu",
      "t": "beklemek",
      "e": "to wait"
    },
    {
      "l": "oyondru",
      "t": "beklemek",
      "e": "to wait"
    },
    {
      "l": "oqondinu",
      "t": "beklemek",
      "e": "to wait"
    },
    {
      "l": "oçu",
      "t": "beklemek",
      "e": "to wait"
    },
    {
      "l": "oyondrinu",
      "t": "bekletmek",
      "e": "to make someone wait"
    },
    {
      "l": "oqondinu",
      "t": "bekletmek",
      "e": "to make someone wait"
    },
    {
      "l": "memgvapu",
      "t": "benzemek",
      "e": "to resemble"
    },
    {
      "l": "memgvapinu",
      "t": "benzetmek",
      "e": "to liken"
    },
    {
      "l": "memgvapu",
      "t": "benziyor halde olmak",
      "e": "to take after"
    },
    {
      "l": "oç̌ǩoru",
      "t": "biçmek",
      "e": "to mow (with a knife/hook)"
    },
    {
      "l": "oç̌ǩiru",
      "t": "biçmek",
      "e": "to mow (with a knife/hook)"
    },
    {
      "l": "oşǩoru",
      "t": "biçmek",
      "e": "to mow (with a knife/hook)"
    },
    {
      "l": "oxerxu",
      "t": "biçmek (testere ile)",
      "e": "to mow (with a saw)"
    },
    {
      "l": "domçinu",
      "t": "bildirmek",
      "e": "to declare, to inform"
    },
    {
      "l": "omçinu",
      "t": "bildirmek",
      "e": "to declare, to inform"
    },
    {
      "l": "memçinu",
      "t": "bildirmek",
      "e": "to declare, to inform"
    },
    {
      "l": "olasiru",
      "t": "bilemek",
      "e": "to grind/sharpen"
    },
    {
      "l": "olast̆u",
      "t": "bilemek",
      "e": "to grind/sharpen"
    },
    {
      "l": "gexunu",
      "t": "binmek",
      "e": "to get on/ride/ascend"
    },
    {
      "l": "cexunu",
      "t": "binmek",
      "e": "to get on/ride/ascend"
    },
    {
      "l": "oǩoğmalu",
      "t": "biriktirmek",
      "e": "to save (money)"
    },
    {
      "l": "oǩobğu",
      "t": "biriktirmek",
      "e": "to save (money)"
    },
    {
      "l": "oǩont̆alu",
      "t": "birleştirmek",
      "e": "to unite/join"
    },
    {
      "l": "oçodinu",
      "t": "bitirmek",
      "e": "to finish/complete"
    },
    {
      "l": "oçodu",
      "t": "bitmek",
      "e": "to end"
    },
    {
      "l": "meşǩidu",
      "t": "boğmak",
      "e": "to strangle"
    },
    {
      "l": "oçalişu",
      "t": "çalışmak",
      "e": "to work"
    },
    {
      "l": "ordu",
      "t": "büyümek ",
      "e": "to grow up"
    }
  ];
  
  // Search function that handles all three languages
  export const processVerbSearch = (searchTerm, verbs = verbList) => {
    if (!searchTerm) return verbs;
    
    const searchLower = searchTerm.toLowerCase().trim();
    return verbs.filter(verb => 
      verb.l.toLowerCase().includes(searchLower) ||
      verb.t.toLowerCase().includes(searchLower) ||
      verb.e.toLowerCase().includes(searchLower)
    );
  };
  
  // Format a verb for display (converts short keys to full names)
  export const formatVerbForDisplay = (verb) => ({
    'Laz Infinitive': verb.l,
    'Turkish Verb': verb.t,
    'English Translation': verb.e
  });
  
  // Format the entire list for display
  export const formatVerbListForDisplay = (verbs = verbList) => 
    verbs.map(formatVerbForDisplay);
  
  // Get verb by Laz infinitive
  export const getVerbByInfinitive = (infinitive) => 
    verbList.find(v => v.l.toLowerCase() === infinitive.toLowerCase());
  
  // Function to check if a verb exists
  export const verbExists = (infinitive) => 
    verbList.some(v => v.l.toLowerCase() === infinitive.toLowerCase());
  