/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/verbs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Verbs */
    get: operations["search_verbs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/verbs/{entry_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Verb */
    get: operations["get_verb"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/conjugations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Conjugations */
    post: operations["conjugate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/conjugation-options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Options
     * @description Option metadata uses the same validation as generation and requests.
     */
    post: operations["conjugation_options"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reverse": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Reverse */
    get: operations["reverse_lookup"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reverse/suggestions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Suggestions */
    get: operations["reverse_suggestions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AnalysisVariant */
    AnalysisVariant: {
      features: components["schemas"]["Features"];
      form: components["schemas"]["Form"];
    };
    /**
     * Causative
     * @enum {string}
     */
    Causative: "none" | "simple" | "double";
    /** Cell */
    Cell: {
      features: components["schemas"]["Features"];
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "unsupported" | "not_generated" | "error";
      /** Forms */
      forms?: components["schemas"]["Form"][];
      /** Reason */
      reason?: string | null;
      /** Message */
      message?: string | null;
    };
    /** ConjugationRequest */
    ConjugationRequest: {
      /** Entry Id */
      entry_id: string;
      /** Dialects */
      dialects?: components["schemas"]["Dialect"][];
      /**
       * Subject
       * @default all
       */
      subject: components["schemas"]["Person"] | "all";
      /** Object */
      object?: components["schemas"]["Person"] | "all" | null;
      /** @default present */
      tense: components["schemas"]["Tense"];
      /** @default indicative */
      mood: components["schemas"]["Mood"];
      /** @default none */
      derivation: components["schemas"]["Derivation"];
      /**
       * Applicative
       * @default false
       */
      applicative: boolean;
      /** @default none */
      causative: components["schemas"]["Causative"];
      /**
       * Optional Preverb
       * @default false
       */
      optional_preverb: boolean;
    };
    /** ConjugationResponse */
    ConjugationResponse: {
      entry: components["schemas"]["Entry"];
      /**
       * Source
       * @enum {string}
       */
      source: "engine" | "database";
      /** Cells */
      cells: components["schemas"]["Cell"][];
    };
    /**
     * Derivation
     * @enum {string}
     */
    Derivation: "none" | "potential" | "passive";
    /**
     * Dialect
     * @enum {string}
     */
    Dialect: "AS" | "PZ" | "FA" | "HO";
    /** Entry */
    Entry: {
      /** Id */
      id: string;
      /** Infinitive */
      infinitive: string;
      verb_class: components["schemas"]["VerbClass"];
      /** English */
      english: string;
      /** Turkish */
      turkish: string;
      /** Variants */
      variants: components["schemas"]["PrincipalPart"][];
      /** Source Row */
      source_row: number;
      /**
       * Issues
       * @default []
       */
      issues: string[];
    };
    /** Features */
    Features: {
      dialect: components["schemas"]["Dialect"];
      subject: components["schemas"]["Person"];
      object?: components["schemas"]["Person"] | null;
      /** @default present */
      tense: components["schemas"]["Tense"];
      /** @default indicative */
      mood: components["schemas"]["Mood"];
      /** @default none */
      derivation: components["schemas"]["Derivation"];
      /**
       * Applicative
       * @default false
       */
      applicative: boolean;
      /** @default none */
      causative: components["schemas"]["Causative"];
      /**
       * Optional Preverb
       * @default false
       */
      optional_preverb: boolean;
    };
    /** Form */
    Form: {
      /** Spelling */
      spelling: string;
      /** Frame */
      frame: string;
      subject: components["schemas"]["Person"];
      object: components["schemas"]["Person"] | null;
      /** Subject Pronoun */
      subject_pronoun: string;
      /** Object Pronoun */
      object_pronoun: string;
      /** Rule */
      rule: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Match */
    Match: {
      features: components["schemas"]["Features"];
      form: components["schemas"]["Form"];
      entry: components["schemas"]["Entry"];
      /** Variants */
      variants: components["schemas"]["AnalysisVariant"][];
    };
    /**
     * Mood
     * @enum {string}
     */
    Mood: "indicative" | "optative" | "imperative" | "negative_imperative";
    /** Option */
    Option: {
      /** Value */
      value: string | boolean | null;
      /** Enabled */
      enabled: boolean;
      /** Reason */
      reason: string | null;
      /** Reason Code */
      reason_code?: string | null;
    };
    /** OptionsResponse */
    OptionsResponse: {
      /** Dialects */
      dialects: components["schemas"]["Dialect"][];
      /** Options */
      options: {
        [key: string]: components["schemas"]["Option"][];
      };
    };
    /**
     * Person
     * @enum {string}
     */
    Person: "1sg" | "2sg" | "3sg" | "1pl" | "2pl" | "3pl";
    /** PrincipalPart */
    PrincipalPart: {
      /** Form */
      form: string;
      /** Dialects */
      dialects: components["schemas"]["Dialect"][];
    };
    /** ReverseResponse */
    ReverseResponse: {
      /**
       * Match Type
       * @enum {string}
       */
      match_type: "exact" | "alternate" | "broad" | "none";
      /** Total */
      total: number;
      /** Matches */
      matches: components["schemas"]["Match"][];
    };
    /** SuggestionsResponse */
    SuggestionsResponse: {
      /** Suggestions */
      suggestions: string[];
    };
    /**
     * Tense
     * @enum {string}
     */
    Tense:
      "present" | "past" | "future" | "past_progressive" | "present_perfect";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * VerbClass
     * @enum {string}
     */
    VerbClass: "IVD" | "TVE" | "TVM";
    /** VerbPage */
    VerbPage: {
      /** Entries */
      entries: components["schemas"]["Entry"][];
      /** Total */
      total: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  search_verbs: {
    parameters: {
      query?: {
        q?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VerbPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_verb: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entry_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Entry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  conjugate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConjugationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConjugationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  conjugation_options: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConjugationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OptionsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reverse_lookup: {
    parameters: {
      query: {
        q: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReverseResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reverse_suggestions: {
    parameters: {
      query?: {
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuggestionsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
